In [1]:
import torch
import torch.nn as nn

In [2]:
lin1 = nn.Linear(4, 3, bias=False)
lin2 = nn.Linear(4, 3, bias=False)

In [3]:
X = torch.randn((2, 2, 4))
w = torch.randn((2, 3, 4))
lin1.weight.data = w[0]
lin2.weight.data = w[1]
with torch.no_grad():
    y1 = lin1(X[0])
    y2 = lin1(X[1])
print(y1)
print(y2)

tensor([[-1.2830,  0.9303, -1.7724],
        [-0.4592,  0.0452,  2.1165]])
tensor([[ 1.1820, -0.9334,  0.8055],
        [ 2.6511, -0.1522,  3.3976]])


In [4]:
torch.einsum('pnm,pbm -> pbn', (w, X))

tensor([[[-1.2830,  0.9303, -1.7724],
         [-0.4592,  0.0452,  2.1165]],

        [[ 0.9075,  1.0648, -1.0378],
         [ 1.4950,  2.5057, -2.4989]]])

In [6]:
class PopLinear(nn.Module):
    def __init__(self, in_features, out_features, pop_size=100, bias=True, *args, **kwargs):
        super(PopLinear, self).__init__(*args, **kwargs)
        self.weight = nn.Parameter(data=torch.randn((pop_size, out_features, in_features)), requires_grad=False)
        if bias:
            self.bias = nn.Parameter(data=torch.randn((pop_size, out_features)), requires_grad=False)
        else:
            self.bias = None
            
    def vectorize(self):
        pass
        
    def forward(self, inp):
        X = torch.einsum('pnm,pbm -> pbn', (self.weight.data, inp))
        if self.bias is not None:
            X += self.bias.data
        return X
    
lin3 = PopLinear(4, 3, 2, bias=False)
lin3.weight.data = w

In [7]:
lin3(X)

tensor([[[-1.2830,  0.9303, -1.7724],
         [-0.4592,  0.0452,  2.1165]],

        [[ 0.9075,  1.0648, -1.0378],
         [ 1.4950,  2.5057, -2.4989]]])